# yamllint configuration
extends: default

rules:
  line-length:
    max: 120
    level: warning
  indentation:
    spaces: 2
    indent-sequences: true
  truthy:
    allowed-values: ["true", "false", "yes", "no", "on", "off"]
  comments:
    min-spaces-from-content: 2
  document-start: disable
  empty-lines:
    max: 2
  key-duplicates: enable
  new-line-at-end-of-file: enable
  trailing-spaces: enable

ignore: |
  .venv/
  venv/
  node_modules/
  *.lock
