defaults:
  batch_size: 32
  dropout_rate: 0.3
  epochs: 500
  hidden_size: 256
  learning_rate: 0.001
  num_layers: 3
  patience: 50
  weight_decay: 0.001
  xgb_colsample_bytree: 0.8
  xgb_learning_rate: 0.1
  xgb_max_depth: 6
  xgb_subsample: 0.8
positions:
  DST:
    batch_size: 64
    best_validation_r2: 0.040905538970460675
    best_validation_mae: 3.6336536093269562
    best_validation_spearman: 0.2891068101233672
    best_validation_ndcg_at_k: null
    catboost_bagging_temperature: 0.943558843810539
    catboost_border_count: 153
    catboost_depth: 9
    catboost_iterations: 2000
    catboost_l2_leaf_reg: 3.58965939573488
    catboost_learning_rate: 0.08428115988868123
    catboost_min_data_in_leaf: 6
    catboost_random_strength: 6.979825211672289
    dropout_rate: 0.2
    epochs: 2000
    hidden_size: 128
    last_tuned: "2025-09-04T19:24:41.921744"
    learning_rate: 0.08428115988868123
    num_layers: 2
    tuning_trials: 5000
    weight_decay: 3.58965939573488
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  QB:
    batch_size: 48
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: 0.2465447373174767
    epochs: 500
    hidden_size: 192
    last_tuned: "2025-09-05T18:42:29.357706"
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.05
    xgb_max_depth: 7
    xgb_subsample: 0.8
  RB:
    batch_size: 240
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: 0.10718475024592788
    epochs: 500
    hidden_size: 512
    last_tuned: "2025-09-05T14:58:55.156265"
    learning_rate: 0.001024946488521555
    num_layers: 4
    tuning_trials: 20
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
  TE:
    batch_size: 64
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: null
    epochs: 400
    hidden_size: 128
    last_tuned: null
    learning_rate: 0.002
    num_layers: 2
    tuning_trials: 0
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  WR:
    batch_size: 192
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: 0.22865977668818122
    epochs: 500
    hidden_size: 160
    last_tuned: "2025-09-05T16:34:17.549667"
    learning_rate: 0.0004445950785400399
    num_layers: 4
    tuning_trials: 100
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
search_ranges:
  batch_size:
    min: 16
    max: 256
    step: 16
  dropout_rate:
    min: 0.1
    max: 0.5
  hidden_size:
    min: 64
    max: 512
    step: 32
  learning_rate:
    min: 1e-4
    max: 5e-2
    log_scale: true
  num_layers:
    min: 1
    max: 4
  weight_decay:
    min: 1e-5
    max: 1e-2
    log_scale: true
