defaults:
  batch_size: 32
  dropout_rate: 0.3
  epochs: 500
  hidden_size: 256
  learning_rate: 0.001
  num_layers: 3
  patience: 50
  weight_decay: 0.001
  xgb_colsample_bytree: 0.8
  xgb_learning_rate: 0.1
  xgb_max_depth: 6
  xgb_subsample: 0.8
positions:
  DST:
    batch_size: 64
    best_validation_r2: 0.05782438766373965
    best_validation_mae: 3.708309687192491
    best_validation_spearman: 0.2516166274255649
    best_validation_ndcg_at_k: null
    catboost_bagging_temperature: 0.2779397711994165
    catboost_border_count: 185
    catboost_depth: 5
    catboost_iterations: 3500
    catboost_l2_leaf_reg: 7.224595318740729
    catboost_learning_rate: 0.07951773559697924
    catboost_min_data_in_leaf: 7
    catboost_random_strength: 0.7760668449262453
    dropout_rate: 0.2
    epochs: 3500
    hidden_size: 128
    last_tuned: '2025-08-22T11:10:00.161164'
    learning_rate: 0.07951773559697924
    num_layers: 2
    tuning_trials: 500
    weight_decay: 7.224595318740729
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  QB:
    batch_size: 48
    best_validation_r2: -1.679262638092041
    best_validation_mae: 5.804365634918213
    best_validation_spearman: -0.22998978666799066
    best_validation_ndcg_at_k: 0.40902902007533365
    dropout_rate: 0.2465447373174767
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T14:56:27.023650'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.05
    xgb_max_depth: 7
    xgb_subsample: 0.8
  RB:
    batch_size: 48
    best_validation_r2: -0.2713441848754883
    best_validation_mae: 5.998381614685059
    best_validation_spearman: 0.4137932637859814
    best_validation_ndcg_at_k: 0.594992834076214
    dropout_rate: 0.2465447373174767
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T14:59:24.573004'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
  TE:
    batch_size: 64
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: 0.25
    epochs: 400
    hidden_size: 128
    last_tuned: null
    learning_rate: 0.002
    num_layers: 2
    tuning_trials: 0
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  WR:
    batch_size: 48
    best_validation_r2: -0.041590332984924316
    best_validation_mae: 5.8081254959106445
    best_validation_spearman: 0.3483362669033034
    best_validation_ndcg_at_k: 0.42747798431386264
    dropout_rate: 0.2465447373174767
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T15:04:54.013486'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
search_ranges:
  batch_size:
    min: 16
    max: 256
    step: 16
  dropout_rate:
    min: 0.1
    max: 0.5
  hidden_size:
    min: 64
    max: 512
    step: 32
  learning_rate:
    min: 1e-4
    max: 5e-2
    log_scale: true
  num_layers:
    min: 1
    max: 4
  weight_decay:
    min: 1e-5
    max: 1e-2
    log_scale: true
