defaults:
  batch_size: 32
  dropout_rate: 0.3
  epochs: 500
  hidden_size: 256
  learning_rate: 0.001
  num_layers: 3
  patience: 50
  weight_decay: 0.001
  xgb_colsample_bytree: 0.8
  xgb_learning_rate: 0.1
  xgb_max_depth: 6
  xgb_subsample: 0.8
positions:
  DST:
    batch_size: 64
    best_validation_r2: 0.0417885281510314
    best_validation_mae: null
    best_validation_spearman: null
    catboost_bagging_temperature: 0.40841695608322587
    catboost_border_count: 52
    catboost_depth: 8
    catboost_iterations: 4500
    catboost_l2_leaf_reg: 8.948434493860997
    catboost_learning_rate: 0.0341454805901834
    catboost_min_data_in_leaf: 5
    catboost_random_strength: 3.594586253137858
    dropout_rate: 0.2
    epochs: 4500
    hidden_size: 128
    last_tuned: "2025-08-21T20:13:00.262748"
    learning_rate: 0.0341454805901834
    num_layers: 2
    tuning_trials: 100
    weight_decay: 8.948434493860997
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  QB:
    batch_size: 16
    best_validation_r2: 0.2919396162033081
    best_validation_mae: null
    best_validation_spearman: null
    dropout_rate: 0.3832290311184182
    epochs: 500
    hidden_size: 256
    last_tuned: "2025-08-22T07:22:35.062277"
    learning_rate: 0.0010253509690168491
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.05
    xgb_max_depth: 7
    xgb_subsample: 0.8
  RB:
    batch_size: 16
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    dropout_rate: 0.11031655633456552
    epochs: 500
    hidden_size: 256
    last_tuned: "2025-08-21T20:48:36.107796"
    learning_rate: 0.03639264345367794
    num_layers: 3
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
  TE:
    batch_size: 64
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    dropout_rate: 0.25
    epochs: 400
    hidden_size: 128
    last_tuned: null
    learning_rate: 0.002
    num_layers: 2
    tuning_trials: 0
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  WR:
    batch_size: 16
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    dropout_rate: 0.31242177333881366
    epochs: 500
    hidden_size: 128
    last_tuned: "2025-08-21T18:43:33.878957"
    learning_rate: 0.0010253509690168491
    num_layers: 2
    tuning_trials: 1
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
search_ranges:
  batch_size:
    min: 16
    max: 256
    step: 16
  dropout_rate:
    min: 0.1
    max: 0.5
  hidden_size:
    min: 64
    max: 512
    step: 32
  learning_rate:
    min: 1e-4
    max: 5e-2
    log_scale: true
  num_layers:
    min: 1
    max: 4
  weight_decay:
    min: 1e-5
    max: 1e-2
    log_scale: true
