defaults:
  batch_size: 32
  dropout_rate: 0.3
  epochs: 500
  hidden_size: 256
  learning_rate: 0.001
  num_layers: 3
  patience: 50
  weight_decay: 0.001
  xgb_colsample_bytree: 0.8
  xgb_learning_rate: 0.1
  xgb_max_depth: 6
  xgb_subsample: 0.8
positions:
  DST:
    batch_size: 64
    best_validation_r2: 0.04331141605243072
    best_validation_mae: 3.6445401949463596
    best_validation_spearman: 0.2661997618714862
    best_validation_ndcg_at_k: null
    catboost_bagging_temperature: 0.3184925303881691
    catboost_border_count: 204
    catboost_depth: 10
    catboost_iterations: 4000
    catboost_l2_leaf_reg: 9.467935384933472
    catboost_learning_rate: 0.028645750609488086
    catboost_min_data_in_leaf: 9
    catboost_random_strength: 1.3679446598447034
    dropout_rate: 0.2
    epochs: 4000
    hidden_size: 128
    last_tuned: '2025-09-03T21:58:26.562233'
    learning_rate: 0.028645750609488086
    num_layers: 2
    tuning_trials: 1000
    weight_decay: 9.467935384933472
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  QB:
    batch_size: 48
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: null
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T16:17:54.700121'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.05
    xgb_max_depth: 7
    xgb_subsample: 0.8
  RB:
    batch_size: 48
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: null
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T14:59:24.573004'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
  TE:
    batch_size: 64
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: null
    epochs: 400
    hidden_size: 128
    last_tuned: null
    learning_rate: 0.002
    num_layers: 2
    tuning_trials: 0
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.1
    xgb_max_depth: 5
    xgb_subsample: 0.8
  WR:
    batch_size: 48
    best_validation_r2: null
    best_validation_mae: null
    best_validation_spearman: null
    best_validation_ndcg_at_k: null
    dropout_rate: null
    epochs: 500
    hidden_size: 192
    last_tuned: '2025-08-22T15:04:54.013486'
    learning_rate: 0.0044809759182149545
    num_layers: 2
    tuning_trials: 5
    weight_decay: 0.001
    xgb_colsample_bytree: 0.8
    xgb_learning_rate: 0.08
    xgb_max_depth: 6
    xgb_subsample: 0.8
search_ranges:
  batch_size:
    min: 16
    max: 256
    step: 16
  dropout_rate:
    min: 0.1
    max: 0.5
  hidden_size:
    min: 64
    max: 512
    step: 32
  learning_rate:
    min: 1e-4
    max: 5e-2
    log_scale: true
  num_layers:
    min: 1
    max: 4
  weight_decay:
    min: 1e-5
    max: 1e-2
    log_scale: true
